name: Build & Test

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.6'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Run DVGA Tests
        run: |
          python3 ./app.py & python3 -m pytest tests/*